### ISSUE TITLE
Will you make a video explaining how to build a package?

### ISSUE THREAD

**Issue by anandijain** [ChrisRackauckas/MyExample.jl#3]
A couple years ago you made a pretty great [https://youtu.be/tx8DRc7_c9I](video).
Will you be making a similar, more up-to-date video?

Thanks!

**Comment by ChrisRackauckas** [comment]
The video is already made and Youtube is already processing it. This repo was made as part of the video 😄

**Comment by ChrisRackauckas** [comment]
https://www.youtube.com/watch?v=QVmU29rCjaA

**Comment by anandijain** [comment]
Awesome vid!
